## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
m1 = np.zeros(10)
print(m1)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


Создать вектор размера 10, заполненный единицами

In [4]:
m2 = np.ones(10)
print(m2)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


Создать вектор размера 10, заполненный числом 2.5

In [5]:
m3 = np.full(10, 2.5)
print(m3)

[ 2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5  2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [7]:
m4 = np.zeros(10)
m4[4] = 1
print(m4)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


Развернуть вектор (первый становится последним)

In [9]:
v1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(v1)
v1 = v1[::-1]
print(v1)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [11]:
m5 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(m5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [14]:
v2 = np.array([1, 2, 0, 0, 4, 0])
print(v2)
print(np.nonzero(v2))

[1 2 0 0 4 0]
(array([0, 1, 4]),)


Создать 3x3 единичную матрицу

In [15]:
print(np.ones((3, 3,)))

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


Создать массив 3x3x3 со случайными значениями

In [16]:
print(np.random.random((3, 3, 3)))

[[[ 0.95634601  0.88116184  0.88382082]
  [ 0.79120313  0.1011707   0.04947367]
  [ 0.18234077  0.33587928  0.61831287]]

 [[ 0.61768535  0.18615049  0.20491761]
  [ 0.73755315  0.01322567  0.69154986]
  [ 0.57240356  0.85491142  0.11556477]]

 [[ 0.98641194  0.72099379  0.10484705]
  [ 0.23055786  0.37078     0.80140244]
  [ 0.33094303  0.80957394  0.56181625]]]


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [19]:
v3 = np.random.random((30))
print(v3)
print(np.mean(v3))

[ 0.1710266   0.57848549  0.60050665  0.52544547  0.41006704  0.16476131
  0.4374481   0.15716452  0.63718278  0.82147689  0.09516623  0.42417356
  0.87421073  0.1668627   0.13364254  0.13023746  0.67777719  0.9742622
  0.99974378  0.72546925  0.89958874  0.71941955  0.59276779  0.14055724
  0.14003274  0.76837395  0.92616827  0.47524986  0.30687189  0.71282066]
0.512898706702


Перемножить матрицы 5x3 и 3x2

In [23]:
m6 = np.random.random((5,3))
m7 = np.random.random((3,2))
print(m6)
print(m7)
print(np.dot(m6, m7))

[[ 0.03788071  0.36992602  0.00170329]
 [ 0.71965879  0.29395571  0.66327602]
 [ 0.47311109  0.12993317  0.22609048]
 [ 0.32849154  0.90707295  0.95032723]
 [ 0.19110686  0.94961028  0.51788021]]
[[ 0.69294708  0.46271558]
 [ 0.08389351  0.96121652]
 [ 0.42821162  0.78635662]]
[[ 0.05801308  0.37444638]
 [ 0.80736893  1.13712391]
 [ 0.43555607  0.52159753]
 [ 0.71066595  1.77118776]
 [ 0.43385541  1.40844774]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [26]:
print(np.linspace(0.0, 1.0, 12)[1:-1])

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


Заменить максимальный элемент на ноль

In [30]:
v4 = np.random.random(12)
print(v4)
v4[v4.argmax()] = 0.0
print(v4)

[ 0.22846864  0.57904995  0.78432937  0.10471819  0.15343491  0.24616582
  0.74024086  0.37151584  0.61616586  0.50847851  0.68216968  0.14126639]
[ 0.22846864  0.57904995  0.          0.10471819  0.15343491  0.24616582
  0.74024086  0.37151584  0.61616586  0.50847851  0.68216968  0.14126639]


Преобразовать массив из float в int

In [32]:
v5 = np.arange(10, dtype=np.float32)
print(v5)
v5 = v5.astype(np.int32)
print(v5)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[0 1 2 3 4 5 6 7 8 9]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [35]:
coords = np.random.random((10,2))
print(coords)
import scipy.spatial
dist = scipy.spatial.distance.cdist(coords,coords)
print(dist)

[[ 0.89787561  0.88138062]
 [ 0.8325097   0.36447741]
 [ 0.16863174  0.38716783]
 [ 0.96319229  0.63869936]
 [ 0.5468771   0.8735201 ]
 [ 0.42029511  0.50065193]
 [ 0.43906131  0.48034776]
 [ 0.59591208  0.83711084]
 [ 0.25789298  0.72986695]
 [ 0.62516962  0.31685346]]
[[ 0.          0.5210198   0.88093298  0.25131745  0.35108652  0.61076794
   0.60937502  0.30519139  0.6576733   0.62694455]
 [ 0.5210198   0.          0.66426562  0.30376902  0.58370408  0.43412484
   0.41015555  0.52854592  0.68095074  0.21273916]
 [ 0.88093298  0.66426562  0.          0.83342341  0.61612344  0.27606719
   0.28603261  0.62049755  0.35413311  0.46192094]
 [ 0.25131745  0.30376902  0.83342341  0.          0.47797398  0.56017358
   0.54752946  0.41744684  0.71116711  0.46673773]
 [ 0.35108652  0.58370408  0.61612344  0.47797398  0.          0.39376856
   0.40768705  0.06107426  0.32271977  0.56214542]
 [ 0.61076794  0.43412484  0.27606719  0.56017358  0.39376856  0.
   0.02764832  0.37953382  0.28091632 

Случайно расположить p элементов в 2D массив

In [36]:
n = 10
p = 15
m8 = np.zeros((n,n))
np.put(m8, np.random.choice(range(n*n), p, replace=False), 1)
print(m8)

[[ 0.  1.  1.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  1.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.  1.  0.  0.  0.  0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [39]:
v6 = np.array([1,2,3,4,5])
print(v6)
v7 = np.zeros(5 + (5-1)*3)
v7[::3+1] = v6
print(v7)

[1 2 3 4 5]
[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


Найти наиболее частое значение в массиве

In [43]:
a = np.array([1,2,3,1,6,1,3,2,1,1,0,0,1,3,2,2,1,4,5,2,8])
print(a)
counts = np.bincount(a)
print(np.argmax(counts))

[1 2 3 1 6 1 3 2 1 1 0 0 1 3 2 2 1 4 5 2 8]
1


Найти n наибольших значений в массиве

In [48]:
a = np.arange(10000)
np.random.shuffle(a)
print(a)
import bottleneck
z = -bottleneck.partition(-a, 10)[:10]
print(z)

[3719 5205 3085 ..., 2863 9665 3262]
[9992 9991 9996 9993 9994 9999 9997 9998 9995 9990]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [10]:
from subprocess import check_output
import pandas as pd
dtype = {
    'cities': 'object',
    'allergens_en': 'object'
}
parse_dates = [
    'created_t', 'last_modified_t'
]
food = pd.read_csv("en.openfoodfacts.org.products.tsv", sep = "\t", header = 0, dtype = dtype, parse_dates = parse_dates, low_memory=False)

Посмотреть первые 5 записей

In [11]:
print(food.head())

            code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957 

Сколько наблюдений в наборе данных?


In [19]:
food.shape

(356027, 163)

Сколько столбцов в наборе данных?

In [20]:
food.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Напечатайте все названия столбцов

In [25]:
names = food.columns.tolist()
print(names)

['code', 'url', 'creator', 'created_t', 'created_datetime', 'last_modified_t', 'last_modified_datetime', 'product_name', 'generic_name', 'quantity', 'packaging', 'packaging_tags', 'brands', 'brands_tags', 'categories', 'categories_tags', 'categories_en', 'origins', 'origins_tags', 'manufacturing_places', 'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_en', 'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo', 'cities', 'cities_tags', 'purchase_places', 'stores', 'countries', 'countries_tags', 'countries_en', 'ingredients_text', 'allergens', 'allergens_en', 'traces', 'traces_tags', 'traces_en', 'serving_size', 'no_nutriments', 'additives_n', 'additives', 'additives_tags', 'additives_en', 'ingredients_from_palm_oil_n', 'ingredients_from_palm_oil', 'ingredients_from_palm_oil_tags', 'ingredients_that_may_be_from_palm_oil_n', 'ingredients_that_may_be_from_palm_oil', 'ingredients_that_may_be_from_palm_oil_tags', 'nutrition_grade_uk', 'nutrition_grade_fr', 'pnns_groups_1', 

Какое название у 105 столбца?

In [26]:
print(names[104])

-glucose_100g


Какой тип наблюдений в 105 столбце?

In [28]:
print(food.dtypes[104])

float64


Как проиндексирован набор данных?

In [34]:
food.index

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            356017, 356018, 356019, 356020, 356021, 356022, 356023, 356024,
            356025, 356026],
           dtype='int64', length=356027)

Каково значение имени продукта в 19-м наблюдении?

In [33]:
food['product_name'][18]

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [38]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep = "\t", header = 0)
chipo.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 216.7+ KB


Как много продуктов стоят более чем $10.00?

In [48]:
chipo[chipo['item_price'].replace('[\$,)]','',regex=True).astype(float) > 10.0]['item_name'].count()

1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [53]:
chipo[['item_name','item_price']]

item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
5                              Chicken Bowl    $10.98 
6                             Side of Chips     $1.69 
7                             Steak Burrito    $11.75 
8                          Steak Soft Tacos     $9.25 
9                             Steak Burrito     $9.25 
10                      Chips and Guacamole     $4.45 
11                     Chicken Crispy Tacos     $8.75 
12                       Chicken Soft Tacos     $8.75 
13                             Chicken Bowl    $11.25 
14                      Chips and Guacamole     $4.45 
15    Chips and Tomatillo-Green Chili Salsa     $2.39 
16                          Chicken Burrito     $8.49 
17                          Chicken Burrito     $8.49 
18                              Canned Soda     $2.18 
19                             Chicken Bowl     $8.75 
20                      Chips and Guacamole     $4.45 
21                         Barbacoa Burrito     $8.99 
22                         Nantucket Nectar     $3.39 
23                          Chicken Burrito    $10.98 
24                                     Izze     $3.39 
25             Chips and Fresh Tomato Salsa     $2.39 
26                             Chicken Bowl     $8.49 
27                         Carnitas Burrito     $8.99 
28                              Canned Soda     $1.09 
29                          Chicken Burrito     $8.49 
...                                     ...        ...
4592                       Barbacoa Burrito    $11.75 
4593                          Carnitas Bowl    $11.75 
4594                          Barbacoa Bowl    $11.75 
4595                           Chicken Bowl     $8.75 
4596                    Chips and Guacamole     $4.45 
4597                      Canned Soft Drink     $1.25 
4598                          Bottled Water     $1.50 
4599                           Chicken Bowl     $8.75 
4600                    Chips and Guacamole     $4.45 
4601                      Canned Soft Drink     $1.25 
4602                       Barbacoa Burrito     $9.25 
4603                       Barbacoa Burrito     $9.25 
4604                           Chicken Bowl     $8.75 
4605                    Chips and Guacamole     $4.45 
4606                      Canned Soft Drink     $1.25 
4607                          Steak Burrito    $11.75 
4608                         Veggie Burrito    $11.25 
4609                      Canned Soft Drink     $1.25 
4610                          Steak Burrito    $11.75 
4611                         Veggie Burrito    $11.25 
4612                          Carnitas Bowl     $9.25 
4613                                  Chips     $2.15 
4614                          Bottled Water     $1.50 
4615                     Chicken Soft Tacos     $8.75 
4616                    Chips and Guacamole     $4.45 
4617                          Steak Burrito    $11.75 
4618                          Steak Burrito    $11.75 
4619                     Chicken Salad Bowl    $11.25 
4620                     Chicken Salad Bowl     $8.75 
4621                     Chicken Salad Bowl     $8.75 

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [58]:
chipo.sort_values(by=['item_name'])

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  
3389                                        [Diet Coke]    $12.98   
341                                         [Diet Coke]     $6.49   
1849                                             [Coke]     $6.49   
1860                                        [Diet Coke]     $6.49   
2713                                             [Coke]     $6.49   
3422                                             [Coke]     $6.49   
553                                         [Diet Coke]     $6.49   
1916                                        [Diet Coke]     $6.49   
1922                                             [Coke]     $6.49   
1937                                        [Diet Coke]     $6.49   
3836                                             [Coke]     $6.49   
298                                            [Sprite]     $6.49   
1976                                        [Diet Coke]     $6.49   
1167                                             [Coke]     $6.49   
3875                                        [Diet Coke] 

Сколько было заказано самого дорогого предмета?

In [70]:
most_expencive = chipo['item_price'].replace('[\$,)]','',regex=True).astype(float).argmax()
chipo['quantity'].loc[[most_expencive]].astype(int)

3598    15
Name: quantity, dtype: int64

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [74]:
chipo[chipo['item_name'] == "Veggie Salad Bowl"]['order_id'].count()

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [78]:
chipo[(chipo['item_name'] == "Canned Soda") & (chipo['quantity'] > 1)]['order_id'].count()

20