In [1]:
import numpy as np

In [5]:
y = np.array([1, 1, 0])
y

array([1, 1, 0])

In [6]:
x = np.array([[1, 3, 5],
              [7, 2, 6],
              [2, 9, 7]])
x

array([[1, 3, 5],
       [7, 2, 6],
       [2, 9, 7]])

In [16]:
def __sort_samples(x, y):
    sorted_idx = x.argsort() 
    return x[sorted_idx], y[sorted_idx]

sorted_x, sorted_y = __sort_samples(x, y)

print(x.argsort())
print(sorted_x)
print(sorted_y)

[[0 1 2]
 [1 2 0]
 [0 2 1]]
[[[1 3 5]
  [7 2 6]
  [2 9 7]]

 [[7 2 6]
  [2 9 7]
  [1 3 5]]

 [[1 3 5]
  [2 9 7]
  [7 2 6]]]
[[1 1 0]
 [1 0 1]
 [1 0 1]]


In [9]:
class_number = np.unique(y).shape[0]
print(class_number)

2


In [15]:
r_border_ids = np.where(sorted_y[:-1] != sorted_y[1:])[0] + 1
r_border_ids

array([1, 1])